package QLForm;

import salon.tienich.Auth;
import salon.ui.Changepass;
import salon.ui.Login;

/**
 *
 * @author hminh
 */
public class QLHome extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public QLHome() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnKhachhang = new javax.swing.JButton();
        btnLichhen = new javax.swing.JButton();
        btnHoadon = new javax.swing.JButton();
        btnPhieuchi = new javax.swing.JButton();
        btnNhansu = new javax.swing.JButton();
        btnKho = new javax.swing.JButton();
        btnSanpham = new javax.swing.JButton();
        btnNhacungcap = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnDichvu = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        btnChiphi = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        btnUudai = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        btnThongke = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        mnuChangepass = new javax.swing.JMenuItem();
        mnuLogout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1250, 650));
        setMinimumSize(new java.awt.Dimension(1250, 650));
        setPreferredSize(new java.awt.Dimension(1250, 650));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("SALON");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(568, 0, -1, 90));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ACADEMY");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, -1, 100));

        btnKhachhang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/khachhang.png"))); // NOI18N
        btnKhachhang.setBorder(null);
        btnKhachhang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhachhangActionPerformed(evt);
            }
        });
        jPanel2.add(btnKhachhang, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 150, 110));

        btnLichhen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Lichhen.png"))); // NOI18N
        btnLichhen.setBorder(null);
        btnLichhen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLichhenActionPerformed(evt);
            }
        });
        jPanel2.add(btnLichhen, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, 150, 110));

        btnHoadon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/hoadon.png"))); // NOI18N
        btnHoadon.setBorder(null);
        btnHoadon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoadonActionPerformed(evt);
            }
        });
        jPanel2.add(btnHoadon, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 400, 150, 110));

        btnPhieuchi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/DSChiphi.png"))); // NOI18N
        btnPhieuchi.setBorder(null);
        btnPhieuchi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhieuchiActionPerformed(evt);
            }
        });
        jPanel2.add(btnPhieuchi, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 400, 150, 110));

        btnNhansu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/nhansu.png"))); // NOI18N
        btnNhansu.setBorder(null);
        btnNhansu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhansuActionPerformed(evt);
            }
        });
        jPanel2.add(btnNhansu, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 150, 110));

        btnKho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/kho.png"))); // NOI18N
        btnKho.setBorder(null);
        btnKho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhoActionPerformed(evt);
            }
        });
        jPanel2.add(btnKho, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 190, 150, 110));

        btnSanpham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/sanpham.png"))); // NOI18N
        btnSanpham.setBorder(null);
        btnSanpham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSanphamActionPerformed(evt);
            }
        });
        jPanel2.add(btnSanpham, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 150, 110));

        btnNhacungcap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/nhaucngcap.png"))); // NOI18N
        btnNhacungcap.setBorder(null);
        btnNhacungcap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhacungcapActionPerformed(evt);
            }
        });
        jPanel2.add(btnNhacungcap, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 150, 110));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NHÂN SỰ");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("KHO");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 310, 40, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CHI PHÍ");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 520, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("LỊCH HẸN");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 520, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("HÓA ĐƠN");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 520, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("KHÁCH HÀNG");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 520, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("NHÀ CUNG CẤP");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("SẢN PHẨM");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, -1, -1));

        btnDichvu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/dichvu.png"))); // NOI18N
        btnDichvu.setBorder(null);
        btnDichvu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDichvuActionPerformed(evt);
            }
        });
        jPanel2.add(btnDichvu, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 190, 150, 110));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("PHIẾU CHI");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 520, -1, -1));

        btnChiphi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/chiphi.png"))); // NOI18N
        btnChiphi.setBorder(null);
        btnChiphi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChiphiActionPerformed(evt);
            }
        });
        jPanel2.add(btnChiphi, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 400, 150, 110));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("ƯU ĐÃI");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 310, -1, -1));

        btnUudai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/uudai.png"))); // NOI18N
        btnUudai.setBorder(null);
        btnUudai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUudaiActionPerformed(evt);
            }
        });
        jPanel2.add(btnUudai, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 190, 150, 110));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("DỊCH VỤ");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 310, -1, -1));

        btnThongke.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/thongke.png"))); // NOI18N
        btnThongke.setBorder(null);
        btnThongke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongkeActionPerformed(evt);
            }
        });
        jPanel2.add(btnThongke, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 400, 150, 110));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("BÁO CÁO THỐNG KÊ");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 520, -1, -1));

        jMenuBar1.setBackground(new java.awt.Color(153, 171, 190));

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/menu_icon.png"))); // NOI18N

        mnuChangepass.setText("Đổi mật khẩu");
        mnuChangepass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuChangepassActionPerformed(evt);
            }
        });
        jMenu5.add(mnuChangepass);

        mnuLogout.setText("Đăng xuất");
        mnuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLogoutActionPerformed(evt);
            }
        });
        jMenu5.add(mnuLogout);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1210, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNhansuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhansuActionPerformed
        // Tạo một instance của form QLNhansu
        QLNhanSu qlNhansu = new QLNhanSu();
        // Hiển thị form QLNhansu
        qlNhansu.setVisible(true);
        // Đóng form QLHome
        dispose();
    }//GEN-LAST:event_btnNhansuActionPerformed

    private void btnNhacungcapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhacungcapActionPerformed
        QLNhacungcap qlNhacungcap = new QLNhacungcap();
        qlNhacungcap.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnNhacungcapActionPerformed

    private void btnSanphamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSanphamActionPerformed
        QLSanpham qlSanpham = new QLSanpham();
        qlSanpham.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnSanphamActionPerformed

    private void btnKhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhoActionPerformed
        QLKho qlKho = new QLKho();
        qlKho.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnKhoActionPerformed

    private void btnDichvuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDichvuActionPerformed
        QLDichVu qlDichvu = new QLDichVu();
        qlDichvu.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnDichvuActionPerformed

    private void btnUudaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUudaiActionPerformed
        QLUuDai qlud = new QLUuDai();
        qlud.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnUudaiActionPerformed

    private void btnKhachhangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhachhangActionPerformed
        QLKhachhang qlkh = new QLKhachhang();
        qlkh.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnKhachhangActionPerformed

    private void btnLichhenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLichhenActionPerformed
        QLLichhen qllh = new QLLichhen();
        qllh.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnLichhenActionPerformed

    private void btnHoadonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoadonActionPerformed
        QLHoadon qlhd = new QLHoadon();
        qlhd.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnHoadonActionPerformed

    private void btnPhieuchiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhieuchiActionPerformed
        QLPhieuchi qlpc = new QLPhieuchi();
        qlpc.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnPhieuchiActionPerformed

    private void btnChiphiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChiphiActionPerformed
        QLChiPhi qlcp = new QLChiPhi();
        qlcp.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnChiphiActionPerformed

    private void btnThongkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongkeActionPerformed
        BaoCaoThongKeSanPham bctk = new BaoCaoThongKeSanPham();
        bctk.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnThongkeActionPerformed

    private void mnuChangepassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuChangepassActionPerformed
        Changepass dmk = new Changepass();
        dmk.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuChangepassActionPerformed

    private void mnuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLogoutActionPerformed
        Login lg = new Login();
        lg.setVisible(true);
        Auth.clear();
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChiphi;
    private javax.swing.JButton btnDichvu;
    private javax.swing.JButton btnHoadon;
    private javax.swing.JButton btnKhachhang;
    private javax.swing.JButton btnKho;
    private javax.swing.JButton btnLichhen;
    private javax.swing.JButton btnNhacungcap;
    private javax.swing.JButton btnNhansu;
    private javax.swing.JButton btnPhieuchi;
    private javax.swing.JButton btnSanpham;
    private javax.swing.JButton btnThongke;
    private javax.swing.JButton btnUudai;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenuItem mnuChangepass;
    private javax.swing.JMenuItem mnuLogout;
    // End of variables declaration//GEN-END:variables
}
